name: chocolatine

on: [push, delete]
env:
  MIRROR_URL: "https://github.com/EpitechPromo2026/B-DOP-200-PAR-2-1-chocolatine-mathis.champin"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Check coding style
        run: |
          docker run --rm -v $(pwd):/app ghcr.io/epitech/coding-style-checker:latest check.sh $(pwd) $(pwd)

  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: check compil
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make
        run: make
        run: |
          OIFS=$IFS
          IFS=','
          for -f in $EXECUTABLES
          for -x in $EXECUTABLES
          do
          ./$fx
          done
          IFS=$OIFS
      timeout-minutes: 2
      - name: make clean
        run:  make clean

  run_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
      - name: Make tests run
        timeout-minutes: 2
        run: make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
